---
- name: Create the node labeller roles
  k8s:
    state: present
    definition: "{{ item | from_yaml }}"
  with_items: "{{ lookup('template', 'kubevirt-node-labeller-roles.yaml.j2').split('\n---\n') | select('search', '(^|\n)[^#]') | list }}"

- name: Create the node labeller daemon set
  k8s:
    state: present
    definition: "{{ lookup('template', 'kubevirt-node-labeller-ds.yaml.j2') | from_yaml }}"
  register: nl

- name: "Refresh node-labeller var"
  k8s:
    state: present
    definition: "{{ lookup('k8s', kind=nl.result.kind, namespace=nl.result.metadata.namespace, resource_name=nl.result.metadata.name) | from_yaml }}"
  register: nl_status

- name: Set UseKVM condition
  k8s_status:
    api_version: kubevirt.io/v1
    kind: KubevirtNodeLabellerBundle
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
    conditions:
    - type: KVMSupport
      status: "{{ use_kvm }}"
      reason: "enabled"
      message: "KVM support is enabled."

- name: Set progressing condition
  k8s_status:
    api_version: kubevirt.io/v1
    kind: KubevirtNodeLabellerBundle
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
    conditions:
    - type: Progressing
      status: "{{ 'True' if nl_status.result.status.currentNumberScheduled != nl_status.result.status.numberReady else 'False' }}"
      reason: "progressing"
      message: "Node-labeller is progressing."

- name:  "Wait for the node-labeller to start"
  k8s_facts:
    api_version: v1
    kind: "{{ nl.result.kind }}"
    name: "{{ nl.result.metadata.name }}"
    namespace: "{{ nl.result.metadata.namespace }}"
  register: nl_status
  delay: 10
  retries: max_retries
  until: nl_status.resources[0].status.currentNumberScheduled == nl_status.resources[0].status.numberReady | default(false)
  ignore_errors: yes

- name: Set available condition
  k8s_status:
    api_version: kubevirt.io/v1
    kind: KubevirtNodeLabellerBundle
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
    conditions:
    - type: Available
      status: "{{ 'True' if nl_status.resources[0].status.currentNumberScheduled > 0 and nl_status.resources[0].status.currentNumberScheduled == nl_status.resources[0].status.numberReady else 'False' }}"
      reason: "available"
      message: "Node-labeller is available."

- name: Set degraded condition 
  k8s_status:
    api_version: kubevirt.io/v1
    kind: KubevirtNodeLabellerBundle
    name: "{{ meta.name }}"
    namespace: "{{ meta.namespace }}"
    conditions:
    - type: Degraded
      status: "{{ 'True' if nl_status.resources[0].status.currentNumberScheduled == 0 or nl_status.resources[0].status.currentNumberScheduled != nl_status.resources[0].status.numberReady else 'False' }}"
      reason: "degraded"
      message: "Node-labeller is degraded."
