---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: kubevirt-node-labeller
  name: kubevirt-node-labeller
  namespace: {{ meta.namespace }}
spec:
  selector:
    matchLabels:
      app: kubevirt-node-labeller
  template:
    metadata:
      labels:
        app: kubevirt-node-labeller
    spec:
      serviceAccount: kubevirt-node-labeller
      containers:
      - name: kubevirt-node-labeller-sleeper
        image: {{ kubevirt_node_labeller }}
        command: ["sleep"]
        args: ["infinity"]
      initContainers:

        - image: {{ kvm_info_nfd_plugin }}
          command: ["/bin/sh","-c"]
          args: ["cp /usr/bin/kvm-caps-info-nfd-plugin /etc/kubernetes/node-feature-discovery/source.d/;"]
          imagePullPolicy: Always
          name: kvm-info-nfd-plugin
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
  
        - image: {{ kubevirt_cpu_nfd_plugin }}
          command: ["/bin/sh","-c"]
          args: ["cp /plugin/dest/kubevirt-cpu-nfd-plugin /etc/kubernetes/node-feature-discovery/source.d/; cp /config/cpu-plugin-configmap.yaml /etc/kubernetes/node-feature-discovery/source.d/cpu-plugin-configmap.yaml;"]
          imagePullPolicy: Always
          name: kubevirt-cpu-nfd-plugin
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
            - mountPath: /config
              name: cpu-config

        - image: {{ libvirt_image }}
          command: ["/bin/sh","-c"]
          args: ["libvirtd -d; chmod o+rw /dev/kvm; virsh domcapabilities --machine q35 --arch x86_64 --virttype kvm > /etc/kubernetes/node-feature-discovery/source.d/virsh_domcapabilities.xml; cp -r /usr/share/libvirt/cpu_map /etc/kubernetes/node-feature-discovery/source.d/"]
          imagePullPolicy: Always
          name: libvirt
          securityContext:
            privileged: true
          resources:
            requests:
              devices.kubevirt.io/kvm: "1"
            limits:
              devices.kubevirt.io/kvm: "1"
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"
        - env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          image: {{ kubevirt_node_labeller }}
          name: kubevirt-node-labeller
          securityContext:
            privileged: true
          resources:
            requests:
              devices.kubevirt.io/kvm: "1"
            limits:
              devices.kubevirt.io/kvm: "1"
          volumeMounts:
            - name: nfd-source
              mountPath: "/etc/kubernetes/node-feature-discovery/source.d/"

      volumes:
        - name: nfd-source
          emptyDir: {}
        - name: cpu-config
          configMap:
            name: kubevirt-cpu-plugin-configmap